CREATE TABLE T_DEMO (
	ID INT NOT NULL AUTO_INCREMENT COMMENT '主键',
	NAME VARCHAR(100) NOT NULL DEFAULT '' COMMENT '名称',
	VERSION_NO TINYINT(2) NOT NULL DEFAULT 1 COMMENT '版本号',
	DEL_FLAG TINYINT(2) NOT NULL DEFAULT 0 COMMENT '删除标记【0-未删除，1-已删除】',
	CREATE_BY VARCHAR(64) DEFAULT '' COMMENT '创建人',
	CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	UPDATE_BY VARCHAR(64) DEFAULT '' COMMENT '更新人',
	UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
	PRIMARY KEY (ID) USING BTREE
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='表设计案例';
ALTER TABLE T_DEMO ADD INDEX index_del_flag (DEL_FLAG);